version: '3.3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    environment:
     - APIKEY=
     - LOGDIR=logs
     - STAGE=local
    volumes:
      - ./logs:/app/logs
